# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-18 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.TextField(),
        ),
    ]
